### Crear una categoría
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Comida",
  "description": "Gastos en alimentación"
}

### Listar todas las categorías
GET http://localhost:8080/api/categories

### Buscar categoría por id
GET http://localhost:8080/api/categories/1

### Actualizar categoría por id
PUT http://localhost:8080/api/categories/1
Content-Type: application/json

{
  "name": "Comida y bebida",
  "description": "Gastos en alimentación y bebidas"
}

### Borrar
DELETE http://localhost:8080/api/categories/1
