spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true